dist: trusty
language: cpp
compiler:
 - g++-6
 - clang-4.0
sudo: false
os:
 - linux
# - osx
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - nialldouglas14@gmail.com

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - george-edison55-precise-backports
#    - george-edison55-cmake-3.x
#    - llvm-toolchain-trusty-4.0
    packages:
    - g++-6
#    - clang-4.0

env:
 - __="link=shared" FLAGS="link=shared"
 - __="link=static" FLAGS="link=static"
 
matrix:
  exclude:
#  - os: osx
#    compiler: g++-6
#  - os: linux
#    compiler: clang-4.0
#    env: __="Documentation" NAME=TravisDocumentation
#  - os: linux
#    env: __="cmake tests osx" NAME=TravisOSXWorker
#  - os: osx
#    env: __="Code bloat tests"
#  - os: osx
#    env: __="Documentation" NAME=TravisDocumentation
#  - os: osx
#    env: __="cmake tests" NAME=TravisLinuxWorker
 
cache:
  apt: true
  directories:
    - boost
    
before_install:
 - rm -rf boost/*
 - if [ ! -f "boost/bootstrap.sh" ]; then
     wget -O boost.tar.bz2 https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2;
     tar xf boost.tar.bz2 -C boost;
     mv boost/boost_1_65_1 .;
     rm -rf boost;
     mv boost_1_65_1 boost;
     ls -l;
     ls -l boost;
     cd boost;
     ./bootstrap.sh;
     cd ..;
     ln -s ../.. boost/libs/outcome;
   fi;
 - ls -l boost/libs/outcome/

script:
 - if [ "$CXX" = "g++" ]; then FLAGS="$FLAGS toolset=gcc-6"; fi;
 - if [ "$CXX" = "clang++" ]; then FLAGS="$FLAGS toolset=clang-4.0 cxxflags=--std=c++14"; fi;
 - cd boost
 - rm -rf bin.v2/libs/outcome
 - ./b2 headers
 - ./b2 libs/outcome/test $FLAGS
 - rm -rf bin.v2/libs/outcome

after_success:
after_failure:
