theme = "boostdoc"
title = "Boost.Outcome documentation"
publishDir = "../html"
pygmentsStyle = "vs"
pygmentsUseClasses = true
PygmentsCodeFences = true
enableGitInfo = true
disableKinds = [ "RSS", "404" ]
relativeURLs = true
uglyURLs  = true

[outputs]
  home = [ "HTML" ]
  
[params]
  snippetsURL = "https://github.com/ned14/boost-outcome/tree/master/doc/src/snippets/"
  editURL = "https://github.com/ned14/boost-outcome/edit/develop/doc/src/content/"
